version: '3'

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mini-douyin-mysql
    restart: always
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mini_douyin
      - MYSQL_ROOT_PASSWORD=mini-douyin
      - TZ=Asia/Shanghai
  redis:
    image: 'redis:latest'
    container_name: mini-douyin-redis
    restart: always
    ports:
      - 6379:6379
  nacos:
    image: nacos/nacos-server
    container_name: mini-douyin-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    restart:
      on-failure
    volumes:
      - /opt/nacos/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
