version: '3'

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mini-douyin-mysql
    restart: always
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mini_douyin
      - MYSQL_ROOT_PASSWORD=mini-douyin
      - TZ=Asia/Shanghai
  redis:
    image: 'redis:latest'
    container_name: mini-douyin-redis
    restart: always
    ports:
      - 6379:6379